// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFsZh_MsqzpOSOdOI4LvQ8ExjvvuIdqs',
    appId: '1:464876798302:web:1cdde1a8c9a1ac60dacfcf',
    messagingSenderId: '464876798302',
    projectId: 'stuhous-236f6',
    authDomain: 'stuhous-236f6.firebaseapp.com',
    storageBucket: 'stuhous-236f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXbhZo__WV4PK8ulqGCIK0fFFBy-WHeY',
    appId: '1:464876798302:android:37270eda6e65606edacfcf',
    messagingSenderId: '464876798302',
    projectId: 'stuhous-236f6',
    storageBucket: 'stuhous-236f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FziHlqizfUuDphwPRbJ5M4_pp1AZaRI',
    appId: '1:464876798302:ios:c7d6668f857450ccdacfcf',
    messagingSenderId: '464876798302',
    projectId: 'stuhous-236f6',
    storageBucket: 'stuhous-236f6.firebasestorage.app',
    iosBundleId: 'com.example.stuHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FziHlqizfUuDphwPRbJ5M4_pp1AZaRI',
    appId: '1:464876798302:ios:c7d6668f857450ccdacfcf',
    messagingSenderId: '464876798302',
    projectId: 'stuhous-236f6',
    storageBucket: 'stuhous-236f6.firebasestorage.app',
    iosBundleId: 'com.example.stuHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJFsZh_MsqzpOSOdOI4LvQ8ExjvvuIdqs',
    appId: '1:464876798302:web:3360a31640dbde7ddacfcf',
    messagingSenderId: '464876798302',
    projectId: 'stuhous-236f6',
    authDomain: 'stuhous-236f6.firebaseapp.com',
    storageBucket: 'stuhous-236f6.firebasestorage.app',
  );
}
